### ISSUE TITLE
Exception thrown by the target of an invocation.

### ISSUE THREAD

**Issue by SebLavK** [Aragas/Bannerlord.MBOptionScreen#18] opened 2020-05-09 00:19 UTC
I recently implemented version 2.0.10 and some users are having the same crash when launching Bannerlord. All have ModLib installed, possibly other MCM mods. I haven't had any issues testing it on its own.

One of the reports included a couple of handy images:

[Error message](https://imgur.com/a/kv7IrBZ)

[Load order](https://imgur.com/a/feEtqOJ)

**Comment by Aragas** [comment] 2020-05-10 11:05
I would recommend them to install MCM 2.0.11-beta2 or the latest v3 beta standalone module
The integrated v2's before 2.0.10 don't play well together without the standalone module.
Will be fixed when v3 is out!

**Comment by kirnosenko** [comment] 2020-05-16 19:09
Hi there. Looks like v3 is here. But with the latest modlib and mcm integrated 2.0.10 seems to be laggy. What is the best way to use it right now?

**Comment by Aragas** [comment] 2020-05-16 23:53
v3 is still not released!
Laggy in which way?

**Comment by kirnosenko** [comment] 2020-05-17 05:39
I put some code in my settings class constructor and got a lot of troubles. The problem is a new instance of settings is created every time I try to get an instance. Can you fix it to recreate an instance when a user changed settings from the options screen?

**Comment by kirnosenko** [comment] 2020-05-17 06:50
Just checked the source. 2.0.10 from nuget has correct instance caching, but 2.0.10 from mcm mod has not.

**Comment by Aragas** [comment] 2020-05-17 08:16
You should not use the assemblies from Nexus!

**Comment by kirnosenko** [comment] 2020-05-17 08:40
Actually I did not. I put in my mod lib from nuget. And everything fine, until we use it with activated libmod and mcm mods.

**Comment by Aragas** [comment] 2020-05-17 09:56
Oh, right, the constructor issue. This is a limitation of both MCM and ModLib, we create an instance of the settings class to get the abstract settings id. I would suggest you to use the settings class as a light data class instead!

**Comment by kirnosenko** [comment] 2020-05-17 10:39
Is there any way to get a callback when settings was changed?

**Comment by Aragas** [comment] 2020-05-17 12:12
MCM checks if the setting clas implements INotifyPropertyChanged, you can implement and use i!

**Closed** 2020-05-22 16:48 UTC
